name: Build Image
run-name: Build Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          file: ./simple-node-app/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
