name: Build Image and Run CodeDeploy
run-name: Build and Deoploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          file: ./simple-node-app/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

  code-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PERSONAL_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PERSONAL_SECRET_KEY }}
          aws-region: eu-central-1
      - name: Zip and Upload Artifacts
        run: |
          zip -r appspec.zip appspec.yml
          aws s3 cp appspec.zip s3://simple-nodejs-app-bucket/appspec.zip
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name prasad-codedeploy-app \
            --deployment-group-name prasad-deployment-group \
            --s3-location bucket=simple-nodejs-app-bucket,key=appspec.zip,bundleType=zip
