name: Run CodeDeploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  code-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PERSONAL_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PERSONAL_SECRET_KEY }}
          aws-region: eu-central-1
      - name: Zip and Upload Artifacts
        run: |
          zip -r app.zip ./simple-node-app
          aws s3 cp app.zip s3://simple-nodejs-app-bucket/app.zip
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name prasad-codedeploy-app \
            --deployment-group-name prasad-deployment-group \
            --s3-location bucket=simple-nodejs-app-bucket,key=app.zip,bundleType=zip
